language: python

python:
  - "2.7"

install:
  - pip install codecov
  - pip install coverage
  # magellan
  - cd magellan
  - pip install -r requirements.txt
  - python setup.py install
  - cd ..

script: 
  # magellan
  - cd magellan
  - python setup.py test
  - coverage run test/_test.py
  - cd ..
  
after_success:
  - codecov
  - bash < (curl -s https://codecov.io/bash)
